services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    environment:
      # INFLUXDB_DB: exampledb
      # INFLUXDB_ADMIN_USER: admin
      # INFLUXDB_ADMIN_PASSWORD: admin12345678
     - DOCKER_INFLUXDB_INIT_MODE=setup
     - DOCKER_INFLUXDB_INIT_USERNAME=admin
     - DOCKER_INFLUXDB_INIT_PASSWORD=admin12345678
     - DOCKER_INFLUXDB_INIT_ORG=myorg
     - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
     - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=Xj-PwQt4kdyt-R2CcEjIRVI7CFW_z9S9hyJNc43-muNhIdMBAyzqYOOKHP5zbnqU984_8aVTIRraVtGfmHOy_A==
    volumes:
      # - ./influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - influxdb-data:/var/lib/influxdb
    ports:
      - "8086:8086"  # Exposes the InfluxDB HTTP API
    networks:
      - monitoring

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   environment:
  #     GF_SECURITY_ADMIN_PASSWORD: adminpassword
  #   ports:
  #     - "3000:3000"  # Exposes the Grafana web UI
  #   depends_on:
  #     - influxdb
  #   networks:
  #     - monitoring
  #   volumes:
  #     - grafana-data:/var/lib/grafana
      # Xj-PwQt4kdyt-R2CcEjIRVI7CFW_z9S9hyJNc43-muNhIdMBAyzqYOOKHP5zbnqU984_8aVTIRraVtGfmHOy_A==

volumes:
  influxdb-data:
  # grafana-data:

networks:
  monitoring:
    driver: bridge